version: 2
jobs:
    build:
        docker:
            - image: golang:1.7.4
        working_directory: /go/src/github.com/ieee0824/circleci-bench
        steps:
            - checkout
            - run:
                name: check go version
                command: |
                    go version
            - run:
                name: start bench 
                command: |
                    time sh -c "go run main.go > result.txt"
